### ISSUE TITLE
Daemon shouldn't finish the story and reset `qa` label after review, if the story is already finished|delivered|accepted.

### ISSUE THREAD

**Issue by iki** [salsaflow/salsaflow-daemon#10]
Steps to reproduce:
1. mark the PT story as `qa+`
2. deliver the PT story
3. close GH review issue
**Current:** Daemon un-delivers the PT story and removes `qa+`.
**Expected:** Daemon shouldn't finish the story and reset `qa` label after review, if the story is already finished|delivered|accepted.
Sometimes it's just QA'd sooner than CR'ed, and it's working flow too.

Slack: https://salsita.slack.com/archives/salsaflow-support/p1444745421000067

**Comment by tchap** [comment]
@iki Not sure how you manage to deliver the story when the review is not finished.

**Comment by iki** [comment]
We usually send the story for:
1. Salsita review at GitHub via salsaflow,
2. for Salsita QA,
3. and for Balfour review at Stash via PR
**at nearly the same time**.
So when they are fast enough, the story is `qa+` (2) and delivered (3) before internal review (1).

**Comment by tchap** [comment]
This is not a supported workflow really, but I will try to do something about it... :neckbeard:

**Comment by iki** [comment]
May the light of SalsaFlow come to our dark side of unsupported workflows, oh Lord!

**Comment by tchap** [comment]
@iki Started working on this, but I am really not sure what is the logic behind. What is QA good for when the code can potentially change when doing code review and fixing review issues? I guess that we need a broader internal discussion for this...

**Comment by tchap** [comment]
In other words, when I am adding `reviewed` label to a story when the associated review issue is closed, how can I be sure that I should be leaving `qa+` there? IMO it should be removed in case the code changed between the addition of `qa+` and `reviewed`...

**Comment by tchap** [comment]
And IMO the whole thing is pretty messed up, if you are doing internal review after the code is marked as delivered :D We would need to add support into SF for this rather different workflow, it is not just about tweaking the daemon I guess. It's similar to the request for post-release code review, like to be able to postpone code review for when the release is done.

**Comment by tchap** [comment]
Will do something about this as a part of #13 I guess.

**Comment by tchap** [comment]
I am closing this, follow #13 to get updates. This is implemented on `develop` now.
