### ISSUE TITLE
Review story #13: The daemon should keep the QA label when moving to story into the reviewed state

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow-daemon#15]
Story being reviewed: [#13](https://github.com/salsaflow/salsaflow-daemon/issues/13)

SF-Issue-Tracker: GitHub Issues
SF-Story-Key: salsaflow/salsaflow-daemon#13

The commits to be reviewed are following:
- [x] fc9c6b0: Pivotal Tracker: Allow for parallel review and QA

---

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by Argimon** [comment]
@tchap What about github issue tracking module (it still removes qa+ label when reviewed)? Pivotal Tracker will have different behaviour than github?

**Comment by tchap** [comment]
I will take a look how that one behaves...

**Comment by tchap** [comment]
True, the daemon is removing the labels when GitHub Issues are being used. I will align this. Will actually create a new issue for that so that you can close this.

**Comment by Argimon** [comment]
@tchap ok. Closing this.
